### ISSUE TITLE
windows 11 and windows server 2012&2016 error

### ISSUE THREAD

**Issue by mabangde** [EddieIvan01/win32api-practice#1]
Adjust debug privilege
Found LSASRV.dll @ 0x7ffddd8c0000, size: 0x181000
Found IV @ 0x7ffddda29658, 7f994ed454dd7e787ad390e5e075c179
Found 3DES key @ 0x223c820005c: 401ca31a764e34adcf89e813e67de70eafefdfe7bde524a8
Found AES key @ 0x223c820028c: e594a174698f1ab40d1fbaa994258012
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Couldn't find the signature of LoginSessionList in memory: 0x0', src\main.rs:209:59
stack backtrace:
   0:     0x7ff62dbb210e - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98

**Comment by EddieIvan01** [comment]
Signature of LoginSessionList in Windows11 got changed.
